version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: usersdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-users.sql:/docker-entrypoint-initdb.d/init-users.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8020:80"
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
      - ./user-data:/usr/src/app/user-data

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
